%~d0
cd %~dp0

call ..\vcvars.bat

cd SDL2-2.0.16

set cmpl=%compile% /D"_UNICODE" /D"UNICODE" /D"HAVE_LIBC" /D"NDEBUG"

%cmpl% src\atomic\SDL_atomic.c
%cmpl% src\atomic\SDL_spinlock.c
%cmpl% src\audio\directsound\SDL_directsound.c
%cmpl% src\audio\disk\SDL_diskaudio.c
%cmpl% src\audio\dummy\SDL_dummyaudio.c
%cmpl% src\audio\SDL_audio.c
%cmpl% src\audio\SDL_audiocvt.c
%cmpl% src\audio\SDL_audiodev.c
%cmpl% src\audio\SDL_audiotypecvt.c
%cmpl% src\audio\SDL_mixer.c
%cmpl% src\audio\SDL_wave.c
%cmpl% src\audio\winmm\SDL_winmm.c
%cmpl% src\audio\wasapi\SDL_wasapi.c
%cmpl% src\audio\wasapi\SDL_wasapi_win32.c
%cmpl% src\core\windows\SDL_hid.c
%cmpl% src\core\windows\SDL_windows.c
%cmpl% src\core\windows\SDL_xinput.c
%cmpl% src\cpuinfo\SDL_cpuinfo.c
%cmpl% src\dynapi\SDL_dynapi.c
%cmpl% src\events\SDL_clipboardevents.c
%cmpl% src\events\SDL_displayevents.c
%cmpl% src\events\SDL_dropevents.c
%cmpl% src\events\SDL_events.c
%cmpl% src\events\SDL_gesture.c
%cmpl% src\events\SDL_keyboard.c
%cmpl% src\events\SDL_mouse.c
%cmpl% src\events\SDL_quit.c
%cmpl% src\events\SDL_touch.c
%cmpl% src\events\SDL_windowevents.c
%cmpl% src\file\SDL_rwops.c
%cmpl% src\filesystem\windows\SDL_sysfilesystem.c
%cmpl% src\haptic\dummy\SDL_syshaptic.c
%cmpl% src\haptic\SDL_haptic.c
%cmpl% src\haptic\windows\SDL_dinputhaptic.c
%cmpl% src\haptic\windows\SDL_windowshaptic.c
%cmpl% src\haptic\windows\SDL_xinputhaptic.c
%cmpl% src\hidapi\SDL_hidapi.c
%cmpl% src\joystick\dummy\SDL_sysjoystick.c
%cmpl% src\joystick\hidapi\SDL_hidapijoystick.c
%cmpl% src\joystick\hidapi\SDL_hidapi_gamecube.c
%cmpl% src\joystick\hidapi\SDL_hidapi_luna.c
%cmpl% src\joystick\hidapi\SDL_hidapi_ps4.c
%cmpl% src\joystick\hidapi\SDL_hidapi_ps5.c
%cmpl% src\joystick\hidapi\SDL_hidapi_rumble.c
%cmpl% src\joystick\hidapi\SDL_hidapi_stadia.c
%cmpl% src\joystick\hidapi\SDL_hidapi_switch.c
%cmpl% src\joystick\hidapi\SDL_hidapi_xbox360.c
%cmpl% src\joystick\hidapi\SDL_hidapi_xbox360w.c
%cmpl% src\joystick\hidapi\SDL_hidapi_xboxone.c
%cmpl% src\joystick\SDL_gamecontroller.c
%cmpl% src\joystick\SDL_joystick.c
%cmpl% src\joystick\virtual\SDL_virtualjoystick.c
%cmpl% src\joystick\windows\SDL_dinputjoystick.c
%cmpl% src\joystick\windows\SDL_mmjoystick.c
%cmpl% src\joystick\windows\SDL_rawinputjoystick.c
%cmpl% src\joystick\windows\SDL_windowsjoystick.c
%cmpl% src\joystick\windows\SDL_windows_gaming_input.c
%cmpl% src\joystick\windows\SDL_xinputjoystick.c
%cmpl% src\libm\e_atan2.c
%cmpl% src\libm\e_exp.c
%cmpl% src\libm\e_fmod.c
%cmpl% src\libm\e_log.c
%cmpl% src\libm\e_log10.c
%cmpl% src\libm\e_pow.c
%cmpl% src\libm\e_rem_pio2.c
%cmpl% src\libm\e_sqrt.c
%cmpl% src\libm\k_cos.c
%cmpl% src\libm\k_rem_pio2.c
%cmpl% src\libm\k_sin.c
%cmpl% src\libm\k_tan.c
%cmpl% src\libm\s_atan.c
%cmpl% src\libm\s_copysign.c
%cmpl% src\libm\s_cos.c
%cmpl% src\libm\s_fabs.c
%cmpl% src\libm\s_floor.c
%cmpl% src\libm\s_scalbn.c
%cmpl% src\libm\s_sin.c
%cmpl% src\libm\s_tan.c
%cmpl% src\loadso\windows\SDL_sysloadso.c
%cmpl% src\locale\SDL_locale.c
%cmpl% src\locale\windows\SDL_syslocale.c
%cmpl% src\misc\SDL_url.c
%cmpl% src\misc\windows\SDL_sysurl.c
%cmpl% src\power\SDL_power.c
%cmpl% src\power\windows\SDL_syspower.c
%cmpl% src\render\direct3d11\SDL_shaders_d3d11.c
%cmpl% src\render\direct3d\SDL_render_d3d.c
%cmpl% src\render\direct3d11\SDL_render_d3d11.c
%cmpl% src\render\direct3d\SDL_shaders_d3d.c
%cmpl% src\render\opengl\SDL_render_gl.c
%cmpl% src\render\opengl\SDL_shaders_gl.c
%cmpl% src\render\opengles2\SDL_render_gles2.c
%cmpl% src\render\opengles2\SDL_shaders_gles2.c
%cmpl% src\render\SDL_d3dmath.c
%cmpl% src\render\SDL_render.c
%cmpl% src\render\SDL_yuv_sw.c
%cmpl% src\render\software\SDL_blendfillrect.c
%cmpl% src\render\software\SDL_blendline.c
%cmpl% src\render\software\SDL_blendpoint.c
%cmpl% src\render\software\SDL_drawline.c
%cmpl% src\render\software\SDL_drawpoint.c
%cmpl% src\render\software\SDL_render_sw.c
%cmpl% src\render\software\SDL_rotate.c
%cmpl% src\SDL.c
%cmpl% src\SDL_assert.c
%cmpl% src\SDL_dataqueue.c
%cmpl% src\SDL_error.c
%cmpl% src\SDL_hints.c
%cmpl% src\SDL_log.c
%cmpl% src\sensor\dummy\SDL_dummysensor.c
%cmpl% src\sensor\SDL_sensor.c
%cmpl% src\sensor\windows\SDL_windowssensor.c
%cmpl% src\stdlib\SDL_crc32.c
%cmpl% src\stdlib\SDL_getenv.c
%cmpl% src\stdlib\SDL_iconv.c
%cmpl% src\stdlib\SDL_malloc.c
%cmpl% src\stdlib\SDL_qsort.c
%cmpl% src\stdlib\SDL_stdlib.c
%cmpl% src\stdlib\SDL_string.c
%cmpl% src\stdlib\SDL_strtokr.c
%cmpl% src\thread\generic\SDL_syscond.c
%cmpl% src\thread\SDL_thread.c
%cmpl% src\thread\windows\SDL_syscond_srw.c
%cmpl% src\thread\windows\SDL_sysmutex.c
%cmpl% src\thread\windows\SDL_syssem.c
%cmpl% src\thread\windows\SDL_systhread.c
%cmpl% src\thread\windows\SDL_systls.c
%cmpl% src\timer\SDL_timer.c
%cmpl% src\timer\windows\SDL_systimer.c
%cmpl% src\video\dummy\SDL_nullevents.c
%cmpl% src\video\dummy\SDL_nullframebuffer.c
%cmpl% src\video\dummy\SDL_nullvideo.c
%cmpl% src\video\SDL_blit.c
%cmpl% src\video\SDL_blit_0.c
%cmpl% src\video\SDL_blit_1.c
%cmpl% src\video\SDL_blit_A.c
%cmpl% src\video\SDL_blit_auto.c
%cmpl% src\video\SDL_blit_copy.c
%cmpl% src\video\SDL_blit_N.c
%cmpl% src\video\SDL_blit_slow.c
%cmpl% src\video\SDL_bmp.c
%cmpl% src\video\SDL_clipboard.c
%cmpl% src\video\SDL_egl.c
%cmpl% src\video\SDL_fillrect.c
%cmpl% src\video\SDL_pixels.c
%cmpl% src\video\SDL_rect.c
%cmpl% src\video\SDL_RLEaccel.c
%cmpl% src\video\SDL_shape.c
%cmpl% src\video\SDL_stretch.c
%cmpl% src\video\SDL_surface.c
%cmpl% src\video\SDL_video.c
%cmpl% src\video\SDL_vulkan_utils.c
%cmpl% src\video\SDL_yuv.c
%cmpl% src\video\windows\SDL_windowsclipboard.c
%cmpl% src\video\windows\SDL_windowsevents.c
%cmpl% src\video\windows\SDL_windowsframebuffer.c
%cmpl% src\video\windows\SDL_windowskeyboard.c
%cmpl% src\video\windows\SDL_windowsmessagebox.c
%cmpl% src\video\windows\SDL_windowsmodes.c
%cmpl% src\video\windows\SDL_windowsmouse.c
%cmpl% src\video\windows\SDL_windowsopengl.c
%cmpl% src\video\windows\SDL_windowsopengles.c
%cmpl% src\video\windows\SDL_windowsshape.c
%cmpl% src\video\windows\SDL_windowsvideo.c
%cmpl% src\video\windows\SDL_windowsvulkan.c
%cmpl% src\video\windows\SDL_windowswindow.c
%cmpl% src\video\yuv2rgb\yuv_rgb.c

lib.exe /OUT:"SDL2.lib" /NOLOGO *.obj
del *.obj

%cmpl% src\main\windows\SDL_windows_main.c

lib.exe /OUT:"SDL2main.lib" /NOLOGO *.obj
del *.obj

move SDL2.lib ..\..\dist\lib\x86\
move SDL2main.lib ..\..\dist\lib\x86\
